### ISSUE TITLE
The documentation repository is down

### ISSUE THREAD

**Issue by manuel-delverme** [SheffieldML/GPyOpt#117]
http://pythonhosted.org/GPyOpt/ gives 404

**Comment by apaleyes** [comment]
We have faced issues uploading docs after the recent release. This is due to deprecation of pypi-hosted documentation - even though the service is on, it is not trivial to do updates there, and we have not figured that out yet. Hopefully we'll be able to resolve this in a couple of days, or move docs elsewhere

**Comment by dominikstrb** [comment]
It has been a couple of days now. Is there a way you could make the documentation available?
Thank you very much!

**Comment by sharpsy** [comment]
Has there been any update on this one and are there other ways to get to the documentation?

**Comment by apaleyes** [comment]
That look a loooong time, but we finally moved to readthedocs: http://gpyopt.readthedocs.io/
