### ISSUE TITLE
Getting this Issue installing with in OS X 10.10, python3.6

### ISSUE THREAD

**Issue by siddsach** [SheffieldML/GPyOpt#131]
Collecting gpyopt
  Downloading GPyOpt-1.2.0.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    /Users/siddharth/anaconda/lib/python3.6/site-packages/scipy/__init__.py:110: UserWarning: Numpy 1.8.2 or above is recommended for this version of scipy (detected version 1.8.1)
      UserWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-0l7k4uyk/gpyopt/setup.py", line 6, in <module>
        from GPyOpt.__version__ import __version__
      File "/private/tmp/pip-build-0l7k4uyk/gpyopt/GPyOpt/__init__.py", line 10, in <module>
        from GPyOpt.core.task.space import Design_space
      File "/private/tmp/pip-build-0l7k4uyk/gpyopt/GPyOpt/core/__init__.py", line 4, in <module>
        from .bo import BO
      File "/private/tmp/pip-build-0l7k4uyk/gpyopt/GPyOpt/core/bo.py", line 8, in <module>
        from ..util.general import best_value
      File "/private/tmp/pip-build-0l7k4uyk/gpyopt/GPyOpt/util/general.py", line 5, in <module>
        from scipy.special import erfc
      File "/Users/siddharth/anaconda/lib/python3.6/site-packages/scipy/special/__init__.py", line 640, in <module>
        from ._ufuncs import *
      File "__init__.pxd", line 155, in init scipy.special._ufuncs
    ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0l7k4uyk/gpyopt/

Help? Maybe I'm missing something simple?

**Comment by alansaul** [comment]
This appears to be a scipy error rather than one specific to GPyOpt (it apperantly arises purely because GPyOpt uses scipy’s erfc function).

I would recommend trying to update both numpy and scipy versions - there is a little warning suggesting that your numpy version, 1.8.2, might not be fully compatible with scipy 1.0.

I see your using anaconda which is useful. As long as you don’t have any specific dependencies (for other projects) on the current scipy and numpy version, try the following:

```
conda upgrade numpy
conda upgrade scipy
```

and then install GPyOpt as you have been trying to. You might also need to upgrade conda itself. If you really need the current version of numpy to be 1.8.2 and to keep the current scipy version, do the above in a virtual environment to create a ‘GPyOpt’ environment.

If this doesn’t work, make sure that the numpy that is being used is really the anaconda version, not one installed seperately, this error could arise if the scipy installed via anaconda is looking at an older version installed not within anaconda.

**Comment by siddsach** [comment]
Thanks! It's working!
