### ISSUE TITLE
Convergence criteria in GPyOpt?

### ISSUE THREAD

**Issue by AliBaheri** [SheffieldML/GPyOpt#149]
Hi Javier!

For some engineering applications it is important to set convergence criteria something rather than just "iteration budget". Furthermore, considering another (simple) convergence criteria such as
`|J(x (i)) - J(x(i-1))| < epsilon` does not provide a robust solution. 

My question is do you have some suggestions to set convergence criteria intelligently? Does GPyOpt provide something in this regard?

Thanks for help.

**Comment by javiergonzalezh** [comment]
Hi @AliBaheri,
In GPyOpt we have a convergence criterion for 'dist(x[i] - x[i-1]<eps', but not for the outputs. It shouldn't be too difficult to implement, you just need to follow the code of the current one. Can you give it a try? 

BTW, nice meeting you in person in NIPS :)

**Comment by apaleyes** [comment]
There is no way to customize GPyOpt in this way with the API alone. However overriding BO class to add this functionality is totally possible.

Alternatively you could look into [Emukit](https://github.com/amzn/emukit) (brought to you by authors of GPyOpt!) which makes stopping condition a first class citizen, and is designed so that such things are easily customizable. It is not yet on feature parity with GPyOpt as far as BO goes, but it has a fair amount of functionality implemented, and is easy to extend. Give it a try!
