### ISSUE TITLE
Setting starting points of the optimization using X and Y

### ISSUE THREAD

**Issue by TaXxER** [SheffieldML/GPyOpt#236]
I have an optimization problem with many parameters (around 200). For my problem I have a couple of quick heuristics that sometimes find quite decent solutions. I would like to feed these as initial solutions to the optimizer using X and Y. However, I having trouble understanding how to properly feed the data set 2-dimensional data, as GPyOpt currently requires.

```
X = np.array([[initial_X_1,initial_X_2]])
Y = np.array([[initial_Y_1, initial_Y_2]])
myProblem = GPyOpt.methods.BayesianOptimization(f=objectiveWrapper, domain=domain, model_type = 'GP', 
                                                X=X, Y=Y,
                                                acquisition_type='MPI', verbosity=True)
```

leads to an "IndexError: index 1 is out of bounds for axis 1 with size 1" at line 215 of GPyOpt/core/task/space.pyc. However, the alternative, 

```
X = np.array([initial_X_1,initial_X_2])
Y = np.array([initial_Y_1, initial_Y_2])
myProblem = GPyOpt.methods.BayesianOptimization(f=objectiveWrapper, domain=domain, model_type = 'GP', 
                                                X=X, Y=Y,
                                                acquisition_type='MPI', verbosity=True)
```
(one square bracket less to make X and Y 1-dimensional to prevent the indexOutOfBounds)

results in an assertionError that tells me that 2 dimensions are required, thrown at line 48 of GPy/core/gp.pyc.

```
---> 48         assert Y.ndim == 2
     49         logger.info("initializing Y")
     50 

AssertionError: 

```

What am I missing here? How could I feed my many-dimensional initial data as X array in the correct way?

**Comment by apaleyes** [comment]
What are the values stored inside `initial_Y_1` and `initial_Y_2`?

**Comment by sdr2002** [comment]
What GPyOpt required is 2 ranks (= dimensionality, ndim) of ndarray for X and Y.
The first rank becomes trial, and then the second rank is about dimension of X or Y for each trial.
Apparently, the last dimension of Y should be 1, meaning that the objective for each trial since GPyOpt only support single objective search.
Hence 
From > 
X = np.array([[initial_X_1,initial_X_2]])
Y = np.array([[initial_Y_1, initial_Y_2]])
To> 
X = np.array([[initial_X_1], [initial_X_2]])
Y = np.array([[initial_Y_1], [initial_Y_2]])

**Comment by apaleyes** [comment]
Assuming `initial_Y_1` and `initial_Y_2` are plain numbers, what @sdr2002 suggests is a correct approach. Thanks!
