### ISSUE TITLE
Strange behavior of plot_acquisition()

### ISSUE THREAD

**Issue by calm85** [SheffieldML/GPyOpt#25]
Hi!
Sometime GPyOpt suggests the sample which is not the maximum of acquisition function. It does not make scene to me. Furthermore, in the following figure, the uncertainty around 0.5 is almost zero, why at that point we see the acquisition is maximized?

![image](https://cloud.githubusercontent.com/assets/19739863/15991548/fb8afc7c-3083-11e6-8da2-747ca632f9a3.png)

OR this figure:
![image](https://cloud.githubusercontent.com/assets/19739863/15991606/6d47bffc-3085-11e6-9273-1d021edcef1c.png)

**Comment by javiergonzalezh** [comment]
The optimization of the acquisition can be hard and sometimes it may fail.
This happens especially at the end of the optimization (of the main
objective) when most of the mass of the acquisition is usually concentrated
in a small region. Unless one of the local (bfgs) optimizers starts in that
region you won't find the optimum since the gradients won't give you any
sensible information. That is the problem in your example, I suspect. A
possible solution is to increase the number of (randomly spread) local
optimizers

Regarding the the point where the acquisition is maximum, note that you are
minimizing the objective function so in your example 0.5 is a sensible
point to explore.

Hope it helps!

Javier

**Comment by javiergonzalezh** [comment]
Although this still may happen occasionally I would expected this behaviour to be corrected in the new release.
