### ISSUE TITLE
Run terminates early

### ISSUE THREAD

**Issue by karthik-hegde** [SheffieldML/GPyOpt#278]
During my runs, I set max_iter using `myBopt.run_optimization(max_iter=steps)`, however I see that the run terminates very early. I noted that it always terminates when the Y value is the same for 2 iterations, but I am pretty sure it is not a global optimum.

Any thoughts on why it would terminate early? What information I can provide to dig deeper?

**Comment by matthew-hsr** [comment]
You may want to try to increase "initial_design_numdata" or try different random seeds to help find the global minimum.

**Comment by apaleyes** [comment]
it is coded so that the run will always terminate if two consecutive suggested points are extremely close, see [this line](https://github.com/SheffieldML/GPyOpt/blob/249b8ff29c52c12ed867f145a627d529372022d8/GPyOpt/core/bo.py#L141).

You can try setting eps to 0, but i would point out that it is extremely uncommon for BO to suggest exact same point. If that happens i would suspect something wrong with param space or the objective. if however two suggested points are not the same, just very close, that means you are getting stuck at local optimum, and there is no point continuing the process. consider different acquisition function and large initial design, as suggested above, to get unstuck

**Comment by ekalosak** [comment]
@karthik-hegde Does this answer your question? Can the issue be closed?
Documented at: https://github.com/SheffieldML/GPyOpt/wiki/FAQ#my-optimization-run-terminates-early

**Comment by karthik-hegde** [comment]
Thank you, that was helpful!
