### ISSUE TITLE
Batch design with LOCAL PENELAZATION and non-myopic Bayesian Optimization

### ISSUE THREAD

**Issue by AliBaheri** [SheffieldML/GPyOpt#49]
Hi,

I have a general question. Dose the results of "local penalization" in bach design is "one ofter the other"? I mean does the "sequence" mater? What is the difference between "local penalization" and the algorithm called GLASSES in non-myopic Bayesian Optimization Paper? It seems in non-myopic Bayesian Optimization the _sequences_ is matter. Is there any implementation for that?

Thanks in advance!

**Comment by javiergonzalezh** [comment]
Hi Ali,

local_penalization is a method to compute batches of points (where the objective can be evaluated in parallel). GLASSES is a sequential method that is non-myopic, that is, the location where *f* is evaluated is selected by taking into account the impact of that evaluation in the future policy. To this  end, it is necessary to pre-compute the steps ahead, which is done by using a batch method, but this is just an artefact to approximate the intractable loss.

In GPyOpt, GLASSES in implemented in a separate branch. Since it is not integrated in the main code interactions with other methods are not possible so far.

Hope it helps!

**Comment by AliBaheri** [comment]
Thanks, for your response.
I found the GLASSES code and run based on my own problem. I am especially interested to see what are the candidate points at each iteration?  For instance, when I specify the `n_ahead = 5` I would like to see 5  points at each iteration. The `.suggested_sample` does not work. Does it the complete code? 
Thanks for your consideration.

Bests,

**Comment by AliBaheri** [comment]
Update: I worked on the code and it seems the `.suggested_sample` works properly. One thing which I have not yet understood is how the `predict_locations` works? I am not able to find `x_star` in this function???
Another thing is when I use the CMA method (of course for 2D problem) and take the number of iterations more than 1, I face withe exception:
`Cannot find cma library, please install it to use this option.`
Which is not true, because it has already installed.
Could you please check it?

**Comment by AliBaheri** [comment]
Hi,
I solved all of the above issues and run to my own problem. However, the method is very slow even for a short horizon length. Is there any way to improve the speed the GLASSES?

**Comment by javiergonzalezh** [comment]
Hi,
Something you can do is to reduce the number of iterations of the DIRECT algorithm when solving the problem. To compute the acquisition is slow, so that may speed the method a bit.

Javier
