### ISSUE TITLE
Mixing batch_size and num_cores

### ISSUE THREAD

**Issue by F-A** [SheffieldML/GPyOpt#55]
When creating an instance of BayesianOptimization with a batch size or number of cores bigger than 1, both values seems to be mixed up:
Especially the batch_size will be used as the number of core. The problem comes from the file _methods/bayesian_optimization.py l.174_:
`self.objective = SingleObjective(self.f, self.batch_size, self.num_cores,self.objective_name`

This does not corresponds to the init function of SingleObjective (_core/task/objective.py l.36_):
`def __init__(self, func, num_cores = 1, objective_name = 'no_name', batch_type = 'synchronous', unfold_args=False, space = None)`

Is it a bug? I'm new to GPyOpt so there might be something I'm missing...

**Comment by javiergonzalezh** [comment]
Hi!
Good point. It is written like that because in principle you want to match the number of simultaneous evaluations you run with the number of cores, but it is true that it is not strictly necessary. When using single evaluations you simply assume that you don't distribute anything. That why there is that issue in the code, which is not a problem in practice, but that we need definitely to change.

Thanks for pointing it out!

**Comment by F-A** [comment]
I actually would need to have a bigger batch size than the number of core (this is how I found this issue).
Indeed, in my case samples do not all have the same "computing" time. Some samples are obtained within 10sec, others after 5 minutes... Using the same batch size as the number of cores, results in having a few cores computing and the rest being idle.

**Comment by javiergonzalezh** [comment]
The different computing time amy be a result of the different optimizations that you have to do 'on the way', such us, optimizing the model, finding the Lipschitz constant, etc.
