### ISSUE TITLE
Processing EI's acquisition function

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPyOpt#66]
What's the reason behind processing the acquisition function in the way shown below?
<img width="627" alt="screen shot 2016-12-20 at 10 05 46 am" src="https://cloud.githubusercontent.com/assets/1993919/21355723/1e3283b2-c69d-11e6-9f1a-61de46f39700.png">

``` python
## Acquisition function:
x_grid = np.arange(bounds[0][0], bounds[0][1], 0.001)
x_grid = x_grid.reshape(len(x_grid),1)

# (1) ACQU
acqu = acquisition_function(x_grid)

# (2) ACQU_NORMALIZED
acqu_normalized = (-acqu - min(-acqu))/(max(-acqu - min(-acqu)))
m, v = model.predict(x_grid)

model.plot_density(bounds[0], alpha=.5)

plt.plot(x_grid, m, 'k-',lw=1,alpha = 0.6)
plt.plot(x_grid, m-1.96*np.sqrt(v), 'k-', alpha = 0.2)
plt.plot(x_grid, m+1.96*np.sqrt(v), 'k-', alpha=0.2)

plt.plot(Xdata, Ydata, 'r.', markersize=10)
plt.axvline(x=suggested_sample[len(suggested_sample)-1],color='k')
factor = max(m+1.96*np.sqrt(v))-min(m-1.96*np.sqrt(v))

# (3) ACQUISITION
acquisition = 0.2*factor*acqu_normalized-abs(min(m-1.96*np.sqrt(v)))-0.25*factor

plt.plot(x_grid,acqu, 'b-',lw=2,label ='Acqu. Original') 
plt.plot(x_grid,acqu_normalized, 'g-',lw=2,label ='Acqu. Normalized') 
plt.plot(x_grid,acquisition, 'r-',lw=2,label ='Acquisition') 

plt.legend(loc='top left')
```

**Comment by javiergonzalezh** [comment]
The EI, MPI etc need to be  maximized to compute the next point. However, most optimizers are designed to minimize and that's why in GPyOpt we optimize (minimize) the negative acquisition. 

The normalized one is just the acquisition we plot in the 1D case. As it is only warped into the interval [0,1] its global maximum doesn't change and is useful for visualization purposes.
