### ISSUE TITLE
Why does MCMC sampling take so much time here?

### ISSUE THREAD

**Issue by 1Reinier** [SheffieldML/GPyOpt#88]
Even acquiring 50 samples can take ages for GPyOpt.
Why is that the case? Is sampling not parallelized?

Or does `n_samples` mean something like the number of repeated MCMC sampling sequences?

**Comment by 1Reinier** [comment]
@javiergonzalezh Is GPyOpt using GPy's HMC or Metropolis-Hastings for MCMC sampling of GP hyperparameters? 

btw, PyMC3 is using Theano as a backend to speed things up.

**Comment by javiergonzalezh** [comment]
It is using HMC that and averaging the acquisitions with respect to the
samples. You can have a look to this
<http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/sampling_hmc.ipynb>
notebook to check the details.

Hope it helps!

**Comment by 1Reinier** [comment]
Okay thanks! Right now, on my fastest workstation default HMC on a GPRegression model takes over 10 minutes to complete for just 50 samples. Don't really understand why.

I might write some HMC code using PyMC3 for my own purposes. Perhaps I can file a pull request later if I have time.

**Comment by javiergonzalezh** [comment]
Cool! I'd be great if you could use a pull request with that! Thanks for the interests!

**Comment by zhenwendai** [comment]
This is because the default setting skips 100 samples for burn-in and takes 100 samples (10 samples for model with 10 interval), which are 200 HMC samples in total. With the default 20 leapfrog steps setting, the HMC sampling requires 4000 gradient steps. That's why it is slow.

Of course, you could always tune the HMC parameters to make it perform better for your problem.
