### ISSUE TITLE
Gaussian noise question

### ISSUE THREAD

**Issue by 1Reinier** [SheffieldML/GPyOpt#89]
Browsing the source code for `GPModel` I found that the Gaussian noise is always set to 0.01 * variance of the initial samples. What is the intuitive reason behind this?

Underestimating the noise can lead to overfitting, inducing the length scales to be too short. Then you'll end up sampling longer until the global maximum is found.

**Comment by lawrennd** [comment]
Are you asking for GPyOpt or GPy? Sounds like a GPy issue to me, not
GPyOpt, so I'll answer accordingly.

The models are normally optimized, so setting to 0.01 is setting gives a
standard deviation that is 10% of the oriignal. The reason for a rule of
thumb setting like this is that there tend to be local optima that are
easily found when the noise is too small or too large. 10% of signal
standard deviation for the noise (I suppose) seemed like a sensible
starting point. In practice, I think there are more issues around the
setting of lengthscales, where we do hear of problems with the standard
initialisation and we haven't put in a data-dependent initialisation.

Actually, this is an area that we know needs looking at, how to do
data-dependent initialisations so that the optimizer doesn't find trivial
modes (for length scales the trivial mode is either very short length
scales or very long).

**Comment by 1Reinier** [comment]
Thanks. It's probably a GPy issue more so than a GPyOpt issue, but it is actually done in the GPyOpt GPModel source too. Assuming the Gaussian Noise is equal across the domain one feasible strategy would be to sample one point in space multiple times and get the (sample-size adjusted) variance of those samples.

**Comment by nrontsis** [comment]
@lawrennd Thanks for the explanation :) Do you have any papers I could read that support your claim:

> The reason for a rule of thumb setting like this is that there tend to be local optima that are
> easily found when the noise is too small or too large.

Cheers,

Nikitas

**Comment by javiergonzalezh** [comment]
That's a good point but the problem in that case is that several rows of
the covariance matrix (as many as data points sampled in the same location)
would be equal and your matrix would be singular. Because of this reason in
GPyOpt you have two stopping criteria. First, the number of iterations,
which is standard and second a threshold (eps) that controls the distance
between the last two collected evaluations (and that stops the optimization
if they are too close).

**Comment by 1Reinier** [comment]
We could add some jitter. Alternatively you could just consider the variance around the sampled y and insert just the mean of the samples into the model during model initialization.

**Comment by lawrennd** [comment]
Unfortunately that's the sort of trick of the trade that is rarely
published. Also not universally true I'm sure.

One plan is to better surface (and encode) ideas like this in GPy.
